use_frameworks!

platform :ios, '9.0'

target 'XFCollectionViewLayout_Example' do
  pod 'XFCollectionViewLayout', :path => '../'

  target 'XFCollectionViewLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
